grep -i "antigen" *enr.txt |  awk '{print $0, "\tantigen"}' > antigen_enriched.txt
grep -i "b_cell" *enr.txt |  awk '{print $0, "\tb_cell"}' > b_cell_enriched.txt
grep -i "b-cell" *enr.txt |  awk '{print $0, "\tb-cell"}' > b-cell_enriched.txt
grep -i "bacteri" *enr.txt |  awk '{print $0, "\tbacteri"}' > bacteri_enriched.txt
grep -i "basophil" *enr.txt |  awk '{print $0, "\tbasophil"}' > basophil_enriched.txt
grep -i "c-type" *enr.txt |  awk '{print $0, "\tc-type"}' > c-type_enriched.txt
grep -i "chemokine" *enr.txt |  awk '{print $0, "\tchemokine"}' > chemokine_enriched.txt
grep -i "chit" *enr.txt |  awk '{print $0, "\tchit"}' > chit_enriched.txt
grep -i "collagen" *enr.txt |  awk '{print $0, "\tcollagen"}' > collagen_enriched.txt
grep -i "complement" *enr.txt |  awk '{print $0, "\tcomplement"}' > complement_enriched.txt
grep -i "cytokine" *enr.txt |  awk '{print $0, "\tcytokine"}' > cytokine_enriched.txt
grep -i "eosinophil" *enr.txt |  awk '{print $0, "\teosinophil"}' > eosinophil_enriched.txt
grep -i "fc_receptor" *enr.txt |  awk '{print $0, "\tfc_receptor"}' > fc_receptor_enriched.txt
grep -i "fung" *enr.txt |  awk '{print $0, "\tfung"}' > fung_enriched.txt
grep -i "histocompatibility" *enr.txt |  awk '{print $0, "\thistocompatibility"}' > histocompatibility_enriched.txt
grep -i "ifn" *enr.txt |  awk '{print $0, "\tifn"}' > ifn_enriched.txt
grep -i "immune" *enr.txt |  awk '{print $0, "\timmune"}' > immune_enriched.txt
grep -i "immuno" *enr.txt |  awk '{print $0, "\timmuno"}' > immuno_enriched.txt
grep -i "inflam" *enr.txt |  awk '{print $0, "\tinflam"}' > inflam_enriched.txt
grep -i "interferon" *enr.txt |  awk '{print $0, "\tinterferon"}' > interferon_enriched.txt
grep -i "interleukin" *enr.txt |  awk '{print $0, "\tinterleukin"}' > interleukin_enriched.txt
grep -i "keratin" *enr.txt |  awk '{print $0, "\tkeratin"}' > keratin_enriched.txt
grep -i "leukocyte" *enr.txt |  awk '{print $0, "\tleukocyte"}' > leukocyte_enriched.txt
grep -i "leukotriene" *enr.txt |  awk '{print $0, "\tleukotriene"}' > leukotriene_enriched.txt
grep -i "lgp" *enr.txt |  awk '{print $0, "\tlgp"}' > lgp_enriched.txt
grep -i "lymphocyt" *enr.txt |  awk '{print $0, "\tlymphocyt"}' > lymphocyt_enriched.txt
grep -i "lysozyme" *enr.txt |  awk '{print $0, "\tlysozyme"}' > lysozyme_enriched.txt
grep -i "macrophage" *enr.txt |  awk '{print $0, "\tmacrophage"}' > macrophage_enriched.txt
grep -i "mannose" *enr.txt |  awk '{print $0, "\tmannose"}' > mannose_enriched.txt
grep -i "mda" *enr.txt |  awk '{print $0, "\tmda"}' > mda_enriched.txt
grep -i "mhc" *enr.txt |  awk '{print $0, "\tmhc"}' > mhc_enriched.txt
grep -i "monocyte" *enr.txt |  awk '{print $0, "\tmonocyte"}' > monocyte_enriched.txt
grep -i "natural_killer" *enr.txt |  awk '{print $0, "\tnatural_killer"}' > natural_killer_enriched.txt
grep -i "neutrophil" *enr.txt |  awk '{print $0, "\tneutrophil"}' > neutrophil_enriched.txt
grep -i "nf-kappa" *enr.txt |  awk '{print $0, "\tnf-kappa"}' > nf-kappa_enriched.txt
grep -i "nlrp" *enr.txt |  awk '{print $0, "\tnlrp"}' > nlrp_enriched.txt
grep -i "nod" *enr.txt |  awk '{print $0, "\tnod"}' > nod_enriched.txt
grep -i "response_to_vir" *enr.txt |  awk '{print $0, "\tresponse_to_vir"}' > response_to_vir_enriched.txt
grep -i "rig-i" *enr.txt |  awk '{print $0, "\trig-i"}' > rig-i_enriched.txt
grep -i "rlr" *enr.txt |  awk '{print $0, "\trlr"}' > rlr_enriched.txt
grep -i "t_cell" *enr.txt |  awk '{print $0, "\tt_cell"}' > t_cell_enriched.txt
grep -i "t-cell" *enr.txt |  awk '{print $0, "\tt-cell"}' > t-cell_enriched.txt
grep -i "tlr" *enr.txt |  awk '{print $0, "\ttlr"}' > tlr_enriched.txt
grep -i "tnf" *enr.txt |  awk '{print $0, "\ttnf"}' > tnf_enriched.txt
grep -i "toll_like" *enr.txt |  awk '{print $0, "\ttoll_like"}' > toll_like_enriched.txt
grep -i "toll-like" *enr.txt |  awk '{print $0, "\ttoll-like"}' > toll-like_enriched.txt
grep -i "tumor_necrosis" *enr.txt |  awk '{print $0, "\ttumor_necrosis"}' > tumor_necrosis_enriched.txt


